name: file_selector_android
description: Android implementation of the file_selector plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/file_selector/file_selector_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.0.1

publish_to: 'none' # Remove this line when we make the first publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      android:
        package: io.flutter.plugins.file_selector
        dartPluginClass: FileSelectorAndroid
        pluginClass: FileSelectorPlugin

dependencies:
  file_selector_platform_interface: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.1.11
  flutter_lints: ^2.0.0
  flutter_plugin_android_lifecycle: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  pigeon: ^3.2.5
