name: file_selector_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  # TODO(eugerossetto): This should be 2.4.0 once it is published.
  file_selector_platform_interface:
    path: ../../file_selector_platform_interface
  file_selector_web:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
